### ISSUE TITLE
Issue #29 Persists

### ISSUE THREAD

**Issue by brimwats** [RafaelGB/obsidian-db-folder#93]
Hello—

See originally #29 

I tried DB folder again. Again it adds things to my YAML that it shouldn't. 

`Metadata: ` should not have `null` added.
`column1: `  is totally added for no reason to all the files within a folder.

![image](https://user-images.githubusercontent.com/73113656/171816523-d57aefaf-1062-470d-af04-b6a188609c60.png)

![image](https://user-images.githubusercontent.com/73113656/171816533-3168740c-16ee-4cff-994d-46de5b45119c.png)

Could this be because I am creating DB Folders from folders that are already folder notes? I'm not sure what else could be causing it. Folder Note compatibility seems important?

**Comment by brimwats** [comment]
Just tested it again. To reproduce, I create a database folder from a folder named `5. Publications` — there is already a file in there named `5. Publications` so db-folder is created as "Untitled Database". I rename it to `5. Publications Database` and then I create a selection column called ThingType.

All files in the folder have their metadata changed from:


```yaml
---
Metadata: 
Created: 2021-02-07 18:56:06
aliases: []
---
```

to

```yaml
---
column1: 
ThingType: 
Metadata: null
Created: 2021-02-07 18:56:06
aliases: 
---
```

**Comment by RafaelGB** [comment]
hi @brimwats . Please attach your database file here and I will try to reproduce it.

Thanks for give it another try, Its now an official plugin and we are working on an stable version. I really appreciate your feedback

**Comment by brimwats** [comment]
> hi @brimwats . Please attach your database file here and I will try to reproduce it.
> 
> Thanks for give it another try, Its now an official plugin and we are working on an stable version. I really appreciate your feedback


Sure, here it is at each step.

1. before the db is added: 
[5. Publications.zip](https://github.com/RafaelGB/obsidian-db-folder/files/8832567/5.Publications.zip)

2. after db is added, but before it is renamed 
[5. Publications-after-db-added.zip](https://github.com/RafaelGB/obsidian-db-folder/files/8832572/5.Publications-after-db-added.zip)

3. after db is renamed:
[5. Publications-after-db-renamed.zip](https://github.com/RafaelGB/obsidian-db-folder/files/8832573/5.Publications-after-db-renamed.zip)


4. After the db is edited. The error is introduced at this stage, and the YAML is modified and I get 

```yaml
column1: 
TestColumn: 
Metadata: null
```

In addition, upon DB creation I get these errors 

![Clipboard Image](https://user-images.githubusercontent.com/73113656/171861867-cadd0ccd-d12a-4e02-95a5-77f1ea27a0bc.jpg)




I think this is the templater one I get from console:
```
Templater Error: Template parsing error, aborting. 
 Bad template syntax

Unexpected token '%'
====================
var tR='',__l,__lP,include=E.include.bind(E),includeFile=E.includeFile.bind(E)
function layout(p,d){__l=p;__lP=d}
const _prs = [];
tR+='---\n\ndatabase-plugin: basic\n\n---\n\n'
_prs.push(%
name: undefined
description: 
columns:
  column1:
    input: text
    key: column1
    accessor: column1
    label: Column 1
    position: 0
config:
  enable_show_state: false
  group_folder_column: 
%);
tR+='rJ2KqXzxQg'
const _rst = await Promise.all(_prs);
tR = tR.replace(/rJ2KqXzxQg/g, () => _rst.shift());
if(__l)tR=await includeFile(__l,Object.assign(tp,{body:tR},__lP))
if(cb){cb(null,tR)} return tR
```

**Comment by brimwats** [comment]
Another error: when I delete column1 from the database view

![image](https://user-images.githubusercontent.com/73113656/171862190-e5df80c5-a428-4844-9209-7d739b26bf90.png)


all my files have an extra TestColumn added

![image](https://user-images.githubusercontent.com/73113656/171862265-d6c26956-82b8-48ce-8118-2d8e69c33811.png)

**Comment by RafaelGB** [comment]
I will add it to the next minor version goal. Thanks!

**Comment by RafaelGB** [comment]
the errors were new configurations of the features of last versions, they are added automatically if missed.

About Templater error is a known issue but without consequences. If you open a new file with <% %> marks, exist a property inside template to run their stuff

Attach a demo where I try to reproduce it but works. I think It was fixed with another bug report. Working on a stable version and I'm focus just on this kind of issues

[Screen Recording 2022-06-03 at 20.03.21.zip](https://github.com/RafaelGB/obsidian-db-folder/files/8834686/Screen.Recording.2022-06-03.at.20.03.21.zip)

**Comment by RafaelGB** [comment]
Check it again when 1.6.3 is avaliable

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes

**Comment by brimwats** [comment]
Initial impression: I am still getting these errors:

![image](https://user-images.githubusercontent.com/73113656/172001655-4f69c6ab-2ebd-480c-b976-0534077a9360.png)

this is the templater error:

```
plugin:templater-obsidian:82 Templater Error: Template parsing error, aborting. 
 Bad template syntax

Unexpected token '%'
====================
var tR='',__l,__lP,include=E.include.bind(E),includeFile=E.includeFile.bind(E)
function layout(p,d){__l=p;__lP=d}
const _prs = [];
tR+='---\n\ndatabase-plugin: basic\n\n---\n\n'
_prs.push(%
name: undefined
description: 
columns:
  column1:
    input: text
    key: column1
    accessor: column1
    label: Column 1
    position: 0
config:
  enable_show_state: false
  group_folder_column: 
%);
tR+='rJ2KqXzxQg'
const _rst = await Promise.all(_prs);
tR = tR.replace(/rJ2KqXzxQg/g, () => _rst.shift());
if(__l)tR=await includeFile(__l,Object.assign(tp,{body:tR},__lP))
if(cb){cb(null,tR)} return tR
```


maybe you should have a fallback for filename + "Database" or "DB Folder Database"?

**Comment by brimwats** [comment]
The YAML edits are still happening:

![image](https://user-images.githubusercontent.com/73113656/172002086-77c4c3a3-71e9-463b-a88f-dcdb51633341.png)


![image](https://user-images.githubusercontent.com/73113656/172002150-b20698e3-9ec3-4297-8d2f-cb55fe92723c.png)


`column1` shouldn't exist
`Metadata` should be  empty, not `null`

for some reason when I add `asdasd` into the Academic Exchange Quarterly `Twst` column it is not saved when i switch back to the database:

![image](https://user-images.githubusercontent.com/73113656/172002494-60c849c6-5412-4dda-a469-120d5cf2dad8.png)

**Comment by brimwats** [comment]
I got a ton of errors and obsidian crashed after I deleted column1. here's what the console said:

```
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
7[Violation] 'setTimeout' handler took <N>ms
plugin:metaedit:5266 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at OnFileModifyAutomatorManager.onFileModify (plugin:metaedit:5266:29)
onFileModify @ plugin:metaedit:5266
await in onFileModify (async)
eval @ plugin:metaedit:5239
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onChange @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFileCreation @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileInternalFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
Promise.then (async)
t.queue @ app.js:1
t.write @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.modify @ app.js:1
eval @ main.ts:192
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
newDatabase @ main.ts:180
eval @ main.ts:227
t.handleEvent @ app.js:1
plugin:metaedit:5266 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at OnFileModifyAutomatorManager.onFileModify (plugin:metaedit:5266:29)
onFileModify @ plugin:metaedit:5266
await in onFileModify (async)
eval @ plugin:metaedit:5239
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onChange @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFileCreation @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileInternalFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
Promise.then (async)
t.queue @ app.js:1
t.write @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.modify @ app.js:1
eval @ plugin:obsidian-list-modfied:766
fulfilled @ plugin:obsidian-list-modfied:36
Promise.then (async)
step @ plugin:obsidian-list-modfied:48
eval @ plugin:obsidian-list-modfied:49
__async @ plugin:obsidian-list-modfied:33
appendLink @ plugin:obsidian-list-modfied:761
eval @ plugin:obsidian-list-modfied:750
eval @ plugin:obsidian-list-modfied:49
__async @ plugin:obsidian-list-modfied:33
eval @ plugin:obsidian-list-modfied:736
eval @ plugin:obsidian-list-modfied:689
Promise.then (async)
after @ plugin:obsidian-list-modfied:682
eval @ plugin:obsidian-list-modfied:688
wrapper @ plugin:obsidian-list-modfied:687
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
t.queue @ app.js:1
e.onCreateOrModify @ app.js:1
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onChange @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFileCreation @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileInternalFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
Promise.then (async)
t.queue @ app.js:1
t.write @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.modify @ app.js:1
eval @ FileManagerService.ts:48
fulfilled @ tslib.es6.js:73
react-table.development.js:1165 Uncaught Error: Duplicate columns were found with ids: "newColumn3" in the columns array above
    at Object.useTable (VM294 plugin:dbfolder:4023:17)
    at Table (VM294 plugin:dbfolder:91496:103)
    at renderWithHooks (VM294 plugin:dbfolder:27122:19)
    at updateFunctionComponent (VM294 plugin:dbfolder:29493:21)
    at beginWork (VM294 plugin:dbfolder:31200:17)
    at HTMLUnknownElement.callCallback (VM294 plugin:dbfolder:16085:15)
    at Object.invokeGuardedCallbackDev (VM294 plugin:dbfolder:16134:17)
    at invokeGuardedCallback (VM294 plugin:dbfolder:16196:32)
    at beginWork$1 (VM294 plugin:dbfolder:36090:8)
    at performUnitOfWork (VM294 plugin:dbfolder:34905:13)
useTable @ react-table.development.js:1165
Table @ Table.tsx:175
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22779
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-dom.development.js:20085 The above error occurred in the <Table> component:

    at Table (plugin:dbfolder:91410:63)
    at Database (plugin:dbfolder:92158:49)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-table.development.js:1165 Uncaught Error: Duplicate columns were found with ids: "newColumn3" in the columns array above
    at Object.useTable (VM294 plugin:dbfolder:4023:17)
    at Table (VM294 plugin:dbfolder:91496:103)
    at renderWithHooks (VM294 plugin:dbfolder:27122:19)
    at updateFunctionComponent (VM294 plugin:dbfolder:29493:21)
    at beginWork (VM294 plugin:dbfolder:31200:17)
    at HTMLUnknownElement.callCallback (VM294 plugin:dbfolder:16085:15)
    at Object.invokeGuardedCallbackDev (VM294 plugin:dbfolder:16134:17)
    at invokeGuardedCallback (VM294 plugin:dbfolder:16196:32)
    at beginWork$1 (VM294 plugin:dbfolder:36090:8)
    at performUnitOfWork (VM294 plugin:dbfolder:34905:13)
```

**Comment by brimwats** [comment]
a screenshot 
![image](https://user-images.githubusercontent.com/73113656/172002866-44f26a25-f98a-4379-9c04-83ae1573324a.png)

**Comment by brimwats** [comment]
ok so I deleted the plugin and folder and reinstalled and reloaded obsidian and it seems more stable now
![image](https://user-images.githubusercontent.com/73113656/172003302-68c6de53-93a6-4316-bda2-81682f20f1bd.png)


![image](https://user-images.githubusercontent.com/73113656/172003305-684ffcc4-e039-473f-9192-7e15ab21524e.png)


weirdly it's not picking up the Twst columns that exist now

**Comment by brimwats** [comment]
It seems like it is working much better now!

![image](https://user-images.githubusercontent.com/73113656/172003392-10d7a6a4-2a8b-4051-b9b6-e517b80aaa2f.png)


![image](https://user-images.githubusercontent.com/73113656/172003394-5aa98333-01fa-4009-939f-8d201e0a726c.png)


![image](https://user-images.githubusercontent.com/73113656/172003397-3c0ce3e7-59dc-418e-8317-9274bc29f00a.png)

**Comment by brimwats** [comment]
the "metadata" nulls were deleted somewhere along the line too!

**Comment by RafaelGB** [comment]
I am happy to read it!

Little by little we still working to improve the plugin :)

**Comment by RafaelGB** [comment]
seems like the update of the plugin in your vault was stuck for some reason
